import React, { createContext, useContext, useState } from 'react';
import { emptyImage, ImageConfig } from '../siteConfig';
import { MediaBrowser } from './MediaBrowser';
import { Image, X } from 'lucide-react';

export const ImageEditorContext = createContext<{ images: Record<string, ImageConfig>; update: (key: string, image: ImageConfig) => void; reset?: (key: string) => void }>({ images: {}, update: () => {} });
export function ImageControl({ imageKey, fallback = '', label = 'Image' }: { imageKey: string; fallback?: string; label?: string; key?: string }) {
  const { images, update, reset } = useContext(ImageEditorContext);
  const value = images[imageKey] || { ...emptyImage, src: fallback };
  const [open, setOpen] = useState(false);
  const change = (patch: Partial<ImageConfig>) => update(imageKey, { ...value, ...patch });
  return <div className="image-control"><h2><Image size={16} /> {label}</h2><label className="studio-field">Image URL<input value={value.src} placeholder="https://… or /uploads/…" onChange={e => change({ src: e.target.value.trim() })} /><small>Paste a public image URL or choose a file below.</small></label>{value.src && <img src={value.src} alt={value.alt || label} className="image-control-preview" />}<button onClick={() => setOpen(true)}>{value.src ? 'Replace / choose saved image' : 'Choose saved / upload image'}</button>{value.src && <><label className="studio-field">Image description (alt text)<input value={value.alt} onChange={e => change({ alt: e.target.value })} /></label><div className="inspector-grid">{(['width', 'height', 'radius'] as const).map(key => <label className="studio-field" key={key}>{key} (px)<input type="number" min="0" max={key === 'radius' ? 200 : 2000} value={value[key]} onChange={e => change({ [key]: Math.max(0, Math.min(key === 'radius' ? 200 : 2000, +e.target.value)) })} /></label>)}</div><p className="studio-hint">Width 0 fills the available space. Height 0 keeps the original proportions.</p><div className="inspector-grid"><label className="studio-field">Fit<select value={value.fit} onChange={e => change({ fit: e.target.value as ImageConfig['fit'] })}>{['cover', 'contain', 'fill'].map(f => <option key={f}>{f}</option>)}</select></label><label className="studio-field">Crop focus<select value={value.position} onChange={e => change({ position: e.target.value as ImageConfig['position'] })}>{['center', 'top', 'bottom', 'left', 'right'].map(p => <option key={p}>{p}</option>)}</select></label></div><label className="studio-field">Alignment<select value={value.align} onChange={e => change({ align: e.target.value as ImageConfig['align'] })}>{['left', 'center', 'right'].map(p => <option key={p}>{p}</option>)}</select></label><button onClick={() => change({ src: '' })}>Remove image from this section</button></>}{reset && <button onClick={() => reset(imageKey)}>Reset image settings</button>}{open && <div className="media-dialog-backdrop" onClick={() => setOpen(false)}><section className="media-dialog" role="dialog" aria-modal="true" aria-label="Choose an image" onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Escape') setOpen(false); }}><header><div><h2>Choose an image</h2><p>Use saved media or upload a new image.</p></div><button autoFocus aria-label="Close image picker" onClick={() => setOpen(false)}><X size={18} /></button></header><MediaBrowser imagesOnly selected={value.src} onSelect={src => { change({ src, alt: value.alt || label }); setOpen(false); }} /></section></div>}</div>;
}
