import React, {createContext,useContext} from 'react';
import { ArrowRight as BaseArrowRight, ArrowUp as BaseArrowUp, ArrowUpRight as BaseArrowUpRight, Award as BaseAward, BadgeCheck as BaseBadgeCheck, BookOpen as BaseBookOpen, Briefcase as BaseBriefcase, Calendar as BaseCalendar, Check as BaseCheck, CheckCircle as BaseCheckCircle, CheckCircle2 as BaseCheckCircle2, Code as BaseCode, Code2 as BaseCode2, Copy as BaseCopy, Cpu as BaseCpu, Database as BaseDatabase, Download as BaseDownload, ExternalLink as BaseExternalLink, FileCode as BaseFileCode, FileText as BaseFileText, FolderGit2 as BaseFolderGit2, Github as BaseGithub, GraduationCap as BaseGraduationCap, Layers as BaseLayers, Layers3 as BaseLayers3, Linkedin as BaseLinkedin, Mail as BaseMail, MapPin as BaseMapPin, Menu as BaseMenu, Monitor as BaseMonitor, Moon as BaseMoon, Phone as BasePhone, Plus as BasePlus, Radio as BaseRadio, Search as BaseSearch, Send as BaseSend, Server as BaseServer, ShieldAlert as BaseShieldAlert, ShieldCheck as BaseShieldCheck, Sparkles as BaseSparkles, Sun as BaseSun, Terminal as BaseTerminal, TestTube as BaseTestTube, Trash2 as BaseTrash2, X as BaseX } from 'lucide-react';
import type {LucideProps} from 'lucide-react';
import {SiteContext} from './siteConfig';
const registry = {ArrowRight:BaseArrowRight,ArrowUp:BaseArrowUp,ArrowUpRight:BaseArrowUpRight,Award:BaseAward,BadgeCheck:BaseBadgeCheck,BookOpen:BaseBookOpen,Briefcase:BaseBriefcase,Calendar:BaseCalendar,Check:BaseCheck,CheckCircle:BaseCheckCircle,CheckCircle2:BaseCheckCircle2,Code:BaseCode,Code2:BaseCode2,Copy:BaseCopy,Cpu:BaseCpu,Database:BaseDatabase,Download:BaseDownload,ExternalLink:BaseExternalLink,FileCode:BaseFileCode,FileText:BaseFileText,FolderGit2:BaseFolderGit2,Github:BaseGithub,GraduationCap:BaseGraduationCap,Layers:BaseLayers,Layers3:BaseLayers3,Linkedin:BaseLinkedin,Mail:BaseMail,MapPin:BaseMapPin,Menu:BaseMenu,Monitor:BaseMonitor,Moon:BaseMoon,Phone:BasePhone,Plus:BasePlus,Radio:BaseRadio,Search:BaseSearch,Send:BaseSend,Server:BaseServer,ShieldAlert:BaseShieldAlert,ShieldCheck:BaseShieldCheck,Sparkles:BaseSparkles,Sun:BaseSun,Terminal:BaseTerminal,TestTube:BaseTestTube,Trash2:BaseTrash2,X:BaseX};
export const iconNames = Object.keys(registry);
export const IconScope = createContext('site');
function makeIcon(name: keyof typeof registry) {
 return function EditableIcon({iconKey=name,...props}: LucideProps & {iconKey?:string;className?:string;style?:React.CSSProperties;strokeWidth?:number;color?:string}) {
 const config=useContext(SiteContext); const scope=useContext(IconScope); const key=scope+':'+iconKey;
 const settings=config.iconOverrides[key]; const Icon=registry[settings?.name as keyof typeof registry] || registry[name];
 return <Icon {...props} data-icon-key={key} data-icon-name={name} strokeWidth={settings?.strokeWidth ?? config.icons.strokeWidth} style={{...props.style,color:settings?.color || config.icons.color || undefined,scale:String((settings?.size ?? config.icons.size)/100)}} />;
 };
}
export const ArrowRight = makeIcon('ArrowRight');
export const ArrowUp = makeIcon('ArrowUp');
export const ArrowUpRight = makeIcon('ArrowUpRight');
export const Award = makeIcon('Award');
export const BadgeCheck = makeIcon('BadgeCheck');
export const BookOpen = makeIcon('BookOpen');
export const Briefcase = makeIcon('Briefcase');
export const Calendar = makeIcon('Calendar');
export const Check = makeIcon('Check');
export const CheckCircle = makeIcon('CheckCircle');
export const CheckCircle2 = makeIcon('CheckCircle2');
export const Code = makeIcon('Code');
export const Code2 = makeIcon('Code2');
export const Copy = makeIcon('Copy');
export const Cpu = makeIcon('Cpu');
export const Database = makeIcon('Database');
export const Download = makeIcon('Download');
export const ExternalLink = makeIcon('ExternalLink');
export const FileCode = makeIcon('FileCode');
export const FileText = makeIcon('FileText');
export const FolderGit2 = makeIcon('FolderGit2');
export const Github = makeIcon('Github');
export const GraduationCap = makeIcon('GraduationCap');
export const Layers = makeIcon('Layers');
export const Layers3 = makeIcon('Layers3');
export const Linkedin = makeIcon('Linkedin');
export const Mail = makeIcon('Mail');
export const MapPin = makeIcon('MapPin');
export const Menu = makeIcon('Menu');
export const Monitor = makeIcon('Monitor');
export const Moon = makeIcon('Moon');
export const Phone = makeIcon('Phone');
export const Plus = makeIcon('Plus');
export const Radio = makeIcon('Radio');
export const Search = makeIcon('Search');
export const Send = makeIcon('Send');
export const Server = makeIcon('Server');
export const ShieldAlert = makeIcon('ShieldAlert');
export const ShieldCheck = makeIcon('ShieldCheck');
export const Sparkles = makeIcon('Sparkles');
export const Sun = makeIcon('Sun');
export const Terminal = makeIcon('Terminal');
export const TestTube = makeIcon('TestTube');
export const Trash2 = makeIcon('Trash2');
export const X = makeIcon('X');
