import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validatePortfolio } from '../validatePortfolio.js';
const config = () => ({version:1,theme:{accent:'#6366f1',background:'#09090b',text:'#ffffff',font:'Arial',radius:16,width:1280,dark:true},sections:[{id:'blog',type:'blog',label:'Blog',visible:true,title:'Stories',body:'',image:'',link:'',background:'',padding:32,align:'left',posts:[{id:'first',title:'First post',body:'Hello',date:'2026-10-02',link:''}]}],navigation:[{id:'blog-link',label:'Blog',href:'#blog'}],icons:{color:'',size:100,strokeWidth:2},content:{candidateInfo:{},contactData:{},candidateStats:[],skillGroups:[],educationData:[],certificationsData:[],sampleCodeSnippets:[]}});
test('accepts custom blog navigation and rejects missing section targets',()=>{const v=config();assert.equal(validatePortfolio(v),true);v.navigation[0].href='#missing';assert.equal(validatePortfolio(v),false);});
test('rejects executable navigation and credential-bearing URLs',()=>{for(const href of ['javascript:alert(1)','https://user:password@example.com']){const v=config();v.navigation[0].href=href;assert.equal(validatePortfolio(v),false);}const v=config();v.navigation[0].href='https://example.com';assert.equal(validatePortfolio(v),true);});
test('rejects duplicate posts and unsafe icon CSS',()=>{const v=config();v.sections[0].posts.push({...v.sections[0].posts[0]});assert.equal(validatePortfolio(v),false);const other=config();other.icons.color='red;display:none';assert.equal(validatePortfolio(other),false);other.icons.color='';other.icons.size=1000;assert.equal(validatePortfolio(other),false);});
test('validates editable icons, skill checkboxes, and section tags',()=>{const v=config();v.iconOverrides={'contact:ContactSection-Phone-5':{name:'Phone',color:'#ffffff',size:100,strokeWidth:2}};v.sections[0].tags=['Java','API'];v.content.skillGroups=[{id:'db',category:'Database',skills:[],featured:false,visible:true,showCheckmarks:true}];assert.equal(validatePortfolio(v),true);v.iconOverrides['contact:ContactSection-Phone-5'].name='UnknownIcon';assert.equal(validatePortfolio(v),false);});
test('rejects injected icon styles and invalid tag or checkbox values',()=>{const v=config();v.iconOverrides={phone:{name:'Phone',color:'red;display:none',size:100,strokeWidth:2}};assert.equal(validatePortfolio(v),false);delete v.iconOverrides;v.sections[0].tags=[{html:'<script>'}];assert.equal(validatePortfolio(v),false);delete v.sections[0].tags;v.content.skillGroups=[{featured:'false'}];assert.equal(validatePortfolio(v),false);});
